---
- hosts: all

  handlers:
    - name: 'Reinicia o Apache'
      service:
        name: apache2
        state: restarted
      become: yes

  tasks:
    - name: 'Instala pacotes de dependência do SO'
      apt:
        name: '{{ item }}'
        state: latest
      become: yes
      with_items:
        - php8
        - apache2
        - libapache2-mod-php8
        - php8-gd
        - php8-mcrypt
        - php8-mysql
        - mysql-server-5.6
        - python-mysqldb

    - name: 'Cria o banco MySQL'
      mysql_db:
        name: wordpress_db
        login_user: root
        state: present

    - name: 'Cria um usuário no MySQL'
      mysql_user:
        login_user: root
        name: Gabriel
        password: cso
        priv: 'wordpress_db.*:ALL'
        state: present

    - name: 'Download do WordPress'
      get_url:
        url: 'https://wordpress.org/latest.tar.gz'
        dest: /tmp/wordpress.tar.gz'

    - name: 'Descompactar o WordPress'
      unarchive:
        src: '/tmp/wordpress.tar.gz'
        dest: /var/www
        remote_src: yes
      become: yes

    - copy:
        src: '/var/www/wordpress/wp-config-sample.php'
        dest: '/var/www/wordpress/wp-config.php'
        remote_src: yes
      become: yes

    - name: 'Configura o wp-config com as entradas do BD'
      replace:
        path: '/var/www/wordpress/wp=config.php'
        regexp: '{{ item.regex }}'
        replace: '{{ item.value }}'
        backup: yes
      with_items:
        - { regex: 'database_name_here', value: 'wordpress_db'}
        - { regex: 'username_here', value: 'wordpress_user'}
        - { regex: 'password_here', value: '12345'}
      become: yes

    - name: 'Configura Apache para servir o Wordpress'
      copy:
        src: 'files/000-default.conf'
        dest: '/etc/apache2/sites-available/000-default.conf'
      become: yes
      notify:
        - restart apache
