---
- hosts: all
  tasks:
    - name: 'Instala pacotes de dependência do SO'
      apt:
        name: '{{ item }}'
        state: latest
      become: yes
      with_items:
        - php8
        - apache2
        - libapache2-mod-php8
