---
hosts: database
  handlers:
    - name: restart mysql
      service:
        name: mysql
        state: restarted
      become: yes

  tasks:
    - name: 'Instala pacotes de dependência do SO'
      apt:
        name: '{{ item }}'
        state: latest
      become: yes
      with_items:
        - mysql-server-5.6
        - python-mysqldb

    - name: 'Cria o banco MySQL'
      mysql_db:
        name: wordpress_db
        login_user: root
        state: present

    - name: 'Cria um usuário no MySQL'
      mysql_user:
        login_user: root
        name: '{{ wp_username }}'
        password: '{{ wp_user_password }}'
        priv: '{{ wp_db_name }}.*:ALL'
        state: present
        host: '{{ item }}'
      with_items:
        - 'localhost'
        - '127.0.0.1'
        - '{{ wp_host_ip }}'

    - name: 'Configura o MySQL para aceitar conexões remotas'
      copy:
        src: 'files/my.cnf'
        dest: '/etc/mysql/my.cnf'
      become: yes
      notify:
        - restart mysql

- hosts: wordpress
  handlers:
    - name: 'Reinicia o Apache'
      service:
        name: apache2
        state: restarted
      become: yes

    - name: 'Download do WordPress'
      get_url:
        url: 'https://wordpress.org/latest.tar.gz'
        dest: /tmp/wordpress.tar.gz'

    - name: 'Descompactar o WordPress'
      unarchive:
        src: '/tmp/wordpress.tar.gz'
        dest: /var/www
        remote_src: yes
      become: yes

    - copy:
        src: '{{ wp_install_dir }}/wp-config-sample.php'
        dest: '{{ wp_install_dir }}/wp-config.php'
        remote_src: yes
      become: yes

    - name: 'Configura o wp-config com as entradas do BD'
      replace:
        path: '{{ wp_install_dir }}/wp-config.php'
        regexp: '{{ item.regex }}'
        replace: '{{ item.value }}'
        backup: yes
      with_items:
        - { regex: 'database_name_here', value: 'wordpress_db' }
        - { regex: 'username_here', value: '{{ wp_username }}' }
        - { regex: 'password_here', value: '{{ wp_user_password }}' }
        - { regex: 'localhost', value: '{{ wp_db_ip }}' }
      become: yes

    - name: 'Configura Apache para servir o Wordpress'
      template:
        src: 'templates/000-default.conf.j2'
        dest: '/etc/apache2/sites-available/000-default.conf'
      become: yes
      notify:
        - restart apache
