---
- name: 'Cria o banco MySQL'
  mysql_db:
    name: wordpress_db
    login_user: root
    state: present

- name: 'Cria um usuário no MySQL'
  mysql_user:
    login_user: root
    name: '{{ wp_username }}'
    password: '{{ wp_user_password }}'
    priv: '{{ wp_db_name }}.*:ALL'
    state: present
    host: '{{ item }}'
  with_items:
    - 'localhost'
    - '127.0.0.1'
    - '{{ wp_host_ip }}'

- name: 'Configura o MySQL para aceitar conexões remotas'
  copy:
    src: 'files/my.cnf'
    dest: '/etc/mysql/my.cnf'
  become: yes
  notify:
    - restart mysql
